### ISSUE TITLE
Left-Click on Flag triggers the bomb

### ISSUE THREAD

**Issue by wtho** [Knochenmark/minesweeper#107]
When a flag is set on a tile and it afterwards left-clicked, the bomb explodes. The "original" windows-minesweeper had a securing mechanism to avoid left-clicks on flags. Flags had to be removed before the bomb can be triggered.

If this is by design, it is ok for me, but it just ruined a hard game for me just before winning.

**Comment by Knochenmark** [comment]
Thanks for reporting, I guess a guard to prevent the left click wouldn't hurt. I will consider it.
