### ISSUE TITLE
Add dropdown or buttons for different difficulties

### ISSUE THREAD

**Issue by Knochenmark** [Knochenmark/minesweeper#7]
The gridsize and amount of mines on the field should be based on the selected difficulty

Some difficulties to start with might be:
- Easy / Beginner
- Normal / Medium
- Hard / Expert

Store selected difficulty in localStorage for convenience

pass the values to the minesweeper component as props

**Comment by psyperl** [comment]
might need to define the gridsize and the amount of mines for the mentioned difficulties.
